# Generated by Django 3.0.8 on 2020-07-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('size', models.CharField(default='', help_text='weight, kg', max_length=50, verbose_name='Size')),
                ('breed', models.CharField(default='Mongrel', max_length=100)),
                ('body', models.CharField(max_length=140)),
                ('age', models.CharField(default='', help_text='y.o.', max_length=50, verbose_name='Age')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
    ]
